import type { Metadata } from 'next'
import { Lato, Roboto } from 'next/font/google'
import './globals.css'
import GlobalState from '@/context'
import Navbar from '@/components/Navbar/Navbar'

const lato = Lato({ 
  weight: ['400', '700'],
  subsets: ['latin'] 
})

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <GlobalState>
          <Navbar />
          <main className='flex flex-col min-h-screen mt-[5rem]'>
            {children}
          </main>
        </GlobalState>
      </body>
    </html>
  )
}
